### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/libpcap-feedstock#1]
For Windows, wait for libpcap-1.9 to be released. CMake support will be better. Use m2-{bison, flex} for build and curl to download WinPcap 
TODO: Find out if wpcap can be built without external dep: WinPcap
https://github.com/the-tcpdump-group/libpcap/blob/master/.appveyor.yml

**Comment by wolfv** [comment]
This looks like it's done now?

**Comment by nehaljwani** [comment]
Yes, closing.
